### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Tornros** [ErikHogberg/5sd063-tzl_we-ll-share-the-flame#128]
- [x] Must - 1 Raise Extinguisher
- [x] Must - 2 Wood under feet (floor)
- [x] Must - 2 Fasten extinguisher
- [ ] Must - Hide/ cover cords
- [ ] Must - Computer placement
- [x] Must - Get screen & stand
- [ ] Must - Make booth safe
- [x] Should - 1 Feet for screen panel
- [x] Could - 3 Green mat
- [ ] Could - 3 Nozzle hanger/ holder
- [ ] Could - 1 Hose
- [x] Could - 1 Paint everything
- [ ] Wish - Flame stickers
- [ ] Wish - Cone placement
- [x] Wish 3 - Make button prettier
